eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/oauth/token
      userAuthorizationUri: http://localhost:9999/oauth/authorize
      clientId: api-gateway
      clientSecret: api-gateway-secret
    resource:
      loadBalanced: true
      userInfoUri: http://auth-service/user
  security:
    sessions: never